services:
  service1:
    build:
      context: ./service1
    environment:
      - PORT=${PORT_SERVICE1:-3001}
    volumes:
      - ./image-cache:${CACHE_DIRECTORY:-/usr/src/app/cache}
    ports:
      - ${PORT_SERVICE1:-3001}:${PORT_SERVICE1:-3001}

  service2:
    depends_on:
      - service1
    build:
      context: ./service2
    environment:
      - PORT=${PORT_SERVICE2:-3002}
      - PORT_SERVICE1=${PORT_SERVICE1:-3001}
    ports:
      - ${PORT_SERVICE2:-3002}:${PORT_SERVICE2:-3002}
